-- V4__create_tokens_table.sql
-- Tokens table for persistent token storage with history
-- Stores all tokens (expired and active) for audit purposes

-- =====================================================
-- TOKENS TABLE
-- =====================================================
CREATE TABLE tokens (
    token VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_tokens_expires_after_created CHECK (expires_at > created_at)
);

-- Indexes for tokens
CREATE INDEX idx_tokens_user ON tokens(user_id);
CREATE INDEX idx_tokens_expires ON tokens(expires_at);
CREATE INDEX idx_tokens_user_expires ON tokens(user_id, expires_at);

COMMENT ON TABLE tokens IS 'User authentication tokens with expiration tracking and full history';
COMMENT ON COLUMN tokens.token IS 'Opaque token string (UUID, auto-generated by database, serves as PRIMARY KEY)';
COMMENT ON COLUMN tokens.user_id IS 'Reference to user who owns this token';
COMMENT ON COLUMN tokens.created_at IS 'Token creation timestamp';
COMMENT ON COLUMN tokens.expires_at IS 'Token expiration timestamp';
